/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AccessKeyData {
  id: string
  namespace: string
  eventType: string
  group: string
  eventPath: string
  eventObjectIdPath?: string
  timestampPath?: string
  parentAccessKey?: string
}
export interface AccessKey {
  environment: string
  eventType: string
  version: number
  data: AccessKeyData
}
export function encodeAccessKey(accessKey: AccessKey, password: string): string
export function decodeAccessKey(accessKey: string, password: string): AccessKey
export function generateId(prefix: string): string
