/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AccessKeyData {
  id: string
  namespace: string
  eventType: string
  group: string
  eventPath: string
  eventObjectIdPath?: string
  timestampPath?: string
  parentAccessKey?: string
}
export interface Options {
  serverUrl: string
}
export interface GetOptions {
  id: string
}
export class IntegrationOS {
  constructor(accessKey: string, options?: Options | undefined | null)
  customers(connectionKey: string): CustomerApi
}
export class Customer {
  id: string
  name: string
  age: number
}
export class CustomerApi {
  constructor()
  get(options: GetOptions): Promise<Response<Customer>>
  list(): Promise<Response<Array<Customer>>>
}
